/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --env-interface CloudflareEnv --include-runtime false --env-file .env.example` (hash: bcb4844226cd478d560415c1a64fb07f)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env {
		APP_SETTINGS_KV: KVNamespace;
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		BETTER_AUTH_URL: string;
		BETTER_AUTH_SECRET: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		AUTH_MICROSOFT_ENTRA_ID_ID: string;
		AUTH_MICROSOFT_ENTRA_ID_SECRET: string;
		AUTH_MICROSOFT_ENTRA_ID_TENANT_ID: string;
		NEWS_API_BASE_URL: string;
		VITE_ADSENSE_CLIENT_ID: string;
		VITE_ADSENSE_SLOT_SIDEBAR: string;
		VITE_ADSENSE_SLOT_HEADER: string;
		VITE_ADSENSE_SLOT_FOOTER: string;
		VITE_ADSENSE_SLOT_INLINE: string;
		VITE_GA_ID: string;
		VITE_VERCEL_ANALYTICS: string;
		VITE_SENTRY_DSN: string;
		SENTRY_AUTH_TOKEN: string;
		VITE_LOG_LEVEL: string;
		ANALYZE: string;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "AUTH_MICROSOFT_ENTRA_ID_ID" | "AUTH_MICROSOFT_ENTRA_ID_SECRET" | "AUTH_MICROSOFT_ENTRA_ID_TENANT_ID" | "NEWS_API_BASE_URL" | "VITE_ADSENSE_CLIENT_ID" | "VITE_ADSENSE_SLOT_SIDEBAR" | "VITE_ADSENSE_SLOT_HEADER" | "VITE_ADSENSE_SLOT_FOOTER" | "VITE_ADSENSE_SLOT_INLINE" | "VITE_GA_ID" | "VITE_VERCEL_ANALYTICS" | "VITE_SENTRY_DSN" | "SENTRY_AUTH_TOKEN" | "VITE_LOG_LEVEL" | "ANALYZE">> {}
}
